spring:
  datasource:
    url: jdbc:postgresql://app-23e7f424-500f-4026-afe5-c29de5396762-do-user-16395802-0.e.db.ondigitalocean.com:25060/chillysradio
    username: chillysradio
    password: AVNS_3QUqLLLOr16TGEHaSvl
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        auto_quote_keyword: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  servlet:
    context-path: /api
#  key_access: oxCIJkAR/pepyVVpChYM3UhUfsjY8jfkSyqp7Do9xFc=
#  key_refresh: T8QmKiJpXwG0OCXyqJRQ0i9IN5/7G37HPmQqKyOoEd4=

springdoc:
  api-docs:
   path: /v3/api-docs        # Путь для доступа к OpenAPI спецификации
  swagger-ui:
    path: /swagger-ui.html # Путь для Swagger UI
    enabled: true
    operations-sorter: method  # Сортировка операций по HTTP методу
    display-request-duration: true  # Отображение времени выполнения запроса
    try-it-out-enabled: true   # Включение возможности "Try it out" для выполнения запросов из UI
  default-produces-media-type: application/json  # Формат данных по умолчанию


