spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chillys_test
    username: postgres
    password: qwerty007
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        auto_quote_keyword: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

#  key_access: oxCIJkAR/pepyVVpChYM3UhUfsjY8jfkSyqp7Do9xFc=
#  key_refresh: T8QmKiJpXwG0OCXyqJRQ0i9IN5/7G37HPmQqKyOoEd4=